PREFIX = /usr

all:

clean:
	${RM} `find -name "*~" -o -name "*.bak"`

install:
	install -d "${PREFIX}/include/3dxware/Xwin"
	install ./xdrvlib.h "${PREFIX}/include"
	install ./3dxware/*.h "${PREFIX}/include/3dxware"
	install ./3dxware/Xwin/*.h "${PREFIX}/include/3dxware/XWin"

