export BASEPREFIX = /usr
export PREFIX = ${BASEPREFIX}
export DEBUG=0
export PLATFORM = LINUX
export SHELL := /bin/bash

SUBDIRS := ./src

runmake = ${MAKE} --no-print-directory -C "$1" -f Makefile.unix "$2"
runmakes = true $(foreach SUB,${SUBDIRS}, && $(call runmake,${SUB},$1))

all:
	@ $(call runmakes,all)

clean:
	@ $(call runmakes,clean)

install:
	@ $(call runmakes,install)

info:
	@ $(call runmakes,info)

