export BASEPREFIX = /usr
export PREFIX = ${BASEPREFIX}
export PLATFORM = DEC
export DEBUG=0
export SHELL := /bin/bash

SUBDIRS := ./cpp ./java

runmake = ${MAKE} --no-print-directory -C "$1" -f Makefile.unix "$2"
runmakes = true $(foreach SUB,${SUBDIRS}, && $(call runmake,${SUB},$1))

all:
	@ $(call runmakes,all)

clean:
	@ $(call runmakes,clean)

install:
	@ $(call runmakes,install)

info:
	@ $(call runmakes,info)

