SUBDIRS := ./src

runmake = ${MAKE} --no-print-directory -C "$1" -f Makefile.linux "$2"
runmakes = true $(foreach SUB,${SUBDIRS}, && $(call runmake,${SUB},$1))

all:
	@ $(call runmakes,all)

clean:
	@ $(call runmakes,clean)

install:
	@ $(call runmakes,install)

info:
	@ $(call runmakes,info)

